version: "3"

services:
    vc_usuario-frontend:
        container_name: vc_usuario-frontend
        build: .
        command: npm run serve
        ports:
            - "8080:8080"
        volumes:
            - .:/app
            - /app/node_modules